### ISSUE TITLE
Settings not attaching to courses

### ISSUE THREAD

**Issue by marilynstefan** [GlobalUniversity/ArkTrainingNetwork#100]
Tried to attach a setting to the course budgeting for business. Used the all about kazak tag
<img width="1143" alt="Screen Shot 2023-03-31 at 11 56 08 AM" src="https://user-images.githubusercontent.com/129228337/229183855-c45df35e-d702-4163-9256-3702742b0f2e.png">
Didn't attach
<img width="1041" alt="Screen Shot 2023-03-31 at 11 57 24 AM" src="https://user-images.githubusercontent.com/129228337/229183910-c951583d-1099-4a62-8e43-582a73c6d625.png">

**Comment by josh-havens** [comment]
Course data model wasn't set up for one-to-many relationships with Branch_Categories.
