### ISSUE TITLE
Language listed in profile

### ISSUE THREAD

**Issue by AyappaA** [GlobalUniversity/ArkTrainingNetwork#107]
Minor, just wondering if the "en" could either be "EN" or even "English", just would look better 

<img width="1170" alt="Screen Shot 2023-03-28 at 6 51 11 PM" src="https://user-images.githubusercontent.com/129342490/229243948-301a0169-cbd7-4dfa-a329-43b64f24d294.png">

**Comment by SAStevens1** [comment]
Done! Added a field in User called languageName, updated that field by querying Language in User_Get_User
