### ISSUE TITLE
Division naming

### ISSUE THREAD

**Issue by AyappaA** [GlobalUniversity/ArkTrainingNetwork#110]
When adding a Division, it says "Division Name Here" but it isn't clear you just need to click there to be able to type the name. Also, when you click, the words are still there and you have to erase them

<img width="807" alt="Screen Shot 2023-03-30 at 1 49 46 PM" src="https://user-images.githubusercontent.com/129342490/229245349-0f024aed-904c-463e-930f-3633aa005436.png">

<img width="807" alt="Screen Shot 2023-03-30 at 1 50 00 PM" src="https://user-images.githubusercontent.com/129342490/229245355-ba7b0b13-3597-4ab4-bf0d-54377c5eaaa6.png">

<img width="807" alt="Screen Shot 2023-03-30 at 1 50 07 PM" src="https://user-images.githubusercontent.com/129342490/229245364-09d3f840-7eaf-42c4-8d4d-ac677c605b84.png">

**Comment by SAStevens1** [comment]
![image](https://user-images.githubusercontent.com/129208341/229569243-8726038c-027a-48bd-b9b5-5f5ba283acc1.png)
When you hover the name the outline appears and I also have added a pointer to provide more assistance. When you click it, it will remove the text so you can type what you desire and if you don't change the title and leave it blank it will revert back to the "Division Name Here" as to not lead to confusing UI/UX later.
