### ISSUE TITLE
Login popup too small for logo pic

### ISSUE THREAD

**Issue by AyappaA** [GlobalUniversity/ArkTrainingNetwork#112]
Is there a way to make the settings so that no matter the size of a photo that is uploaded, it won't make the popup need a scroll bar

 
<img width="914" alt="Screen Shot 2023-04-03 at 6 52 38 PM" src="https://user-images.githubusercontent.com/129342490/229652036-2708a4be-8fc3-4284-9540-51ad49cd6246.png">

**Comment by josh-havens** [comment]
Tweaked a few settings to help a bit. To an extent the scrollbar will always need to show because of landscape views on mobile devices.
