### ISSUE TITLE
Unable to switch Program to Credits/CEUs" in draft

### ISSUE THREAD

**Issue by AyappaA** [GlobalUniversity/ArkTrainingNetwork#114]
Maybe this is by design, but I don't see a way to switch my program while still in the draft/editing stage (or I'm missing where it can be switched); I know it has been said that Pathway isn't ready yet anyway, so maybe that is contributing to that

**Comment by josh-havens** [comment]
Once the choice is made in the original creation, we can't allow changes because we don't want to mix types if courses/containers already exist on the program. Any ideas on how we can make that UX clearer?
