### ISSUE TITLE
Effective vs Start Date in Programs

### ISSUE THREAD

**Issue by AyappaA** [GlobalUniversity/ArkTrainingNetwork#115]
When creating a program it says "effective date" while editing, but viewing the programs in Active or Draft they say "start date"

<img width="944" alt="Screen Shot 2023-04-03 at 7 27 13 PM" src="https://user-images.githubusercontent.com/129342490/229657866-27dec204-fdfb-4f8a-b3ac-536ca1d4877b.png">

<img width="995" alt="Screen Shot 2023-04-03 at 7 46 50 PM" src="https://user-images.githubusercontent.com/129342490/229657875-766b976c-5f15-4000-b481-744e47f67fab.png">

**Comment by josh-havens** [comment]
Need to change the label to keep the two consistent.

**Comment by kdegarmo** [comment]
Changed effective date to start date.
