### ISSUE TITLE
Active Program start date blank

### ISSUE THREAD

**Issue by AyappaA** [GlobalUniversity/ArkTrainingNetwork#116]
Went in to settings of an active program, the start date was blank. This program is a Pathway, but I found another active program that was Academic and it did the same thing

<img width="645" alt="Screen Shot 2023-04-03 at 7 38 45 PM" src="https://user-images.githubusercontent.com/129342490/229658406-c67e854f-bbc4-4176-a457-3793cf392109.png">

<img width="858" alt="Screen Shot 2023-04-03 at 7 39 34 PM" src="https://user-images.githubusercontent.com/129342490/229658424-12bdd8c9-1f35-48a8-ba9c-de7689a09199.png">

**Comment by josh-havens** [comment]
Need to add something to the click/postload to put the dates on the screen from the variable.

**Comment by SAStevens1** [comment]
Disable Past Date was checked in the Date Picker, so I unchecked it and now it works?
