### ISSUE TITLE
Student Degree Audit Apply Transfer Credit

### ISSUE THREAD

**Issue by josh-havens** [GlobalUniversity/ArkTrainingNetwork#120]
Applying a transfer credit/advanced standing to a requirement doesn't update the data on the screen (maybe at all).

**Comment by josh-havens** [comment]
Bad UX, need to not allow/show a message if the course from education history is already used. Need to also clear "Used" courses from Education History if the degree audit is cleared/reset.

**Comment by ChrisLamberth** [comment]
Fixed the issue where transfer credit wasn't being applied. There was an issue with a switch/case where a case needed to be set as "default" so the api call would happen.

I think the issue where we stop courses from being applied and reset their status should be a new feature as it will require more development.
