### ISSUE TITLE
Can only see Active Courses

### ISSUE THREAD

**Issue by AyappaA** [GlobalUniversity/ArkTrainingNetwork#122]
Went to courses, clicked on arrow by "Active Courses" to see the draft/archived ones, nothing showed up. Every time I click, it just refreshes the same page and shows the active courses again. Created a new course and still cannot get to it in Drafts. Every time I click the arrow this same info shows up. (Don't know if this is a permissions thing, but permissions show I have access to the other course types; maybe related to issue #121)

<img width="1435" alt="Screen Shot 2023-04-04 at 7 01 29 PM" src="https://user-images.githubusercontent.com/129342490/229953545-1651f724-d0e7-4845-b703-97746855d30e.png">

**Comment by SAStevens1** [comment]
![image](https://user-images.githubusercontent.com/129208341/230146371-f6c785e7-6604-4416-943b-ebf95e35ebd9.png)

The UI/UX has changed When you click the filter icon to the left it will have a select that you can navigate to Active, Draft, Upcoming and Archived
