### ISSUE TITLE
Store Management > Discount > Main Page > Next page click appears not to work.

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#151]
top and bottom pagination ">" are both broken and both page number fields don’t let me type

**Comment by skruegergu** [comment]
Okay, great!

**Comment by kdegarmo** [comment]
Update: the clicks are now created and appear functional except for the next page click.

**Comment by skruegergu** [comment]
the next click page had a vlc caller mismapped. I mapped it an now it's functional. I'm closing this.
