### ISSUE TITLE
Store Management > Discount > Edit Page > Generate Single Use Batch > no clear feedback why you cant generate a batch before the discount is created

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#154]
should probably have some feedback that you need to create before you can generate

**Comment by SAStevens1** [comment]
Based on the context given with the > This is where I ended up and what appeared when I tried to generate a single use code(batch?)

![Image](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129208341/0cb66cd9-13df-4a0f-847c-ee9159cea9db)

If so I feel like its self explanatory? You can't generate a code for something that doesn't exist yet(discount)

If this is not what you meant, please provide some more information, screenshot, etc. and I'll reopen the issue
