### ISSUE TITLE
Publish Confirmation Modal in Form Builder

### ISSUE THREAD

**Issue by SAStevens1** [GlobalUniversity/ArkTrainingNetwork#160]
![image](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129208341/a4c32826-2c2b-4ed7-b370-4d0b080dac80)

This modal description should probably be reworded so we sound more professional haha

**Comment by MrBonham** [comment]
Upon confirmation this form will be published and can be found in the Active Tab. 
^ new message applied to this issue
