### ISSUE TITLE
Student Active course

### ISSUE THREAD

**Issue by MrBonham** [GlobalUniversity/ArkTrainingNetwork#17]
This is what my new student sees when they click on a course they got enrolled in. 

![image](https://user-images.githubusercontent.com/128522455/228043668-76927298-3bf1-4227-b3f0-b53fef180565.png)

**Comment by josh-havens** [comment]
Removed the progress bar for the moment in Course_Viewer_Outline_Menu. The progress bar element is broken by a javascript library SBBD added back in December.

**Comment by josh-havens** [comment]
Took runtime build #940 from SBBD that contained a javascript library fix for the progress bar and record elements.
