### ISSUE TITLE
Form Builder multiple choice question - options

### ISSUE THREAD

**Issue by SAStevens1** [GlobalUniversity/ArkTrainingNetwork#176]
![image](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129208341/7ecdfa32-a6d0-4e6b-85ff-5e3a502cbd10)

After adding a new option to a multiple choice question, you can grab right below the option and drag it outside the question itself. If you hit the Add Option button it returns to the list. Sometimes. Also after dragging

**Comment by MrBonham** [comment]
After saving it does not keep it outside the list. Do the options need to be able to click and drag?

**Comment by SAStevens1** [comment]
After some discussion with Chris we will not be actively fixing this as it could mess up the ability to reorder the options which we want to give the ability to do.

**Comment by SAStevens1** [comment]
Mark ended up fixing this when he fixed the reordering bug
