### ISSUE TITLE
Form Builder- adding a question to a section erases data in other questions.

### ISSUE THREAD

**Issue by SAStevens1** [GlobalUniversity/ArkTrainingNetwork#178]
![image](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129208341/6f2090fb-7ffd-4171-ab30-81e74e63972f)

Added 5 question types, added a new question and all the data from the previous questions were gone.

**Comment by MrBonham** [comment]
It does not clear out all of the questions Email seems stay when adding a question. Another save issue with forms.

**Comment by ChrisLamberth** [comment]
Added Form_Builder_Question_Save as a keyup to every question type CC's question text input so it saves the question text as the user types the question text.
