### ISSUE TITLE
Should there be a field that shows up here if Administrators haven't added Academic Statuses yet? I could see someone submitting it being empty as a bug.

### ISSUE THREAD

**Issue by MrBonham** [GlobalUniversity/ArkTrainingNetwork#18]
![image](https://user-images.githubusercontent.com/128522455/228044114-26403f34-7b6e-4207-a815-2cbced32e013.png)

**Comment by ChrisLamberth** [comment]
I added an Initial Label value to this dropdown. This won't help if a Branch Administrator hasn't defined any Academic Status' however.
