### ISSUE TITLE
Student Dashboard > Notifications > notification not clickable

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#183]
Student Dashboard > Notifications > The notification is not clickable

<img width="479" alt="Screen Shot 2023-07-05 at 10 37 37 AM" src="https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/f4333172-66e3-4adc-a39c-ee0fa9f854bd">

**Comment by kdegarmo** [comment]
added navigate_to_user_notifications click listener to notification panel so the user can click on the notification and navigate to their notifications.
