### ISSUE TITLE
Student Dashboard > Most Recent Program > clicking it takes you to a completely empty course

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#184]
Student Dashboard > Most Recent Program > clicking "Looks like you don't have a recent program" takes you to a completely empty course

<img width="1036" alt="Screen Shot 2023-07-05 at 11 09 23 AM" src="https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/bfb1799e-0ae5-49e9-9c9f-34f4bf6547a1">
<img width="1381" alt="Screen Shot 2023-07-05 at 11 09 38 AM" src="https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/3e8b69d0-4a89-4d87-b41a-59d9cbd33411">

**Comment by SAStevens1** [comment]
This needs a click to take you to the Student's Current Program in Student Records, One might already exist and just wasn't set, or one will need to be made

**Comment by MrBonham** [comment]
I took the navigate to course. click off of the no courses list. They would have to go to Marketplace or My courses which is on the main menu already.
