### ISSUE TITLE
Student Profile > History > it generates a blank error modal

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#185]
Student Profile > History > clicking the history tab generates a blank error modal
<img width="665" alt="Screen Shot 2023-07-05 at 10 59 22 AM" src="https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/5a7e610e-e557-4aad-8641-0cd61892ad5e">

**Comment by MrBonham** [comment]
The Web Call in "Student_History_Main_Preload" is not returning anything. The Get might need to be added to permissions list. It would return more info. The model shows up when no results are returned. I think this is supposed to be the userID that shows up.

**Comment by MrBonham** [comment]
The modal did not have mappings I am not sure what error messages are supposed to show up. It might need some extra help but it does not show up.
