### ISSUE TITLE
Student Login: Forum - enter key doesnt work while searching.

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#19]
Striking enter produces no action. The search button must be clicked. Furthermore, the key up listener isnt present. I believe that's incongruent with all other search bars in this system.
![Student](https://user-images.githubusercontent.com/129097082/228046592-624c3d7b-4066-4fd4-8fef-244717a00011.png)

**Comment by MrBonham** [comment]
Clicked the box to allow the search to go when enter is pressed. Key up listener can be added as well I did not add it because it might make the search if it has too many responses.
