### ISSUE TITLE
Student > Cart Overlay > goes beyond bottom of the page

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#190]
if i add one more, you wont be able to select "checkout." we might need to truncate the cart overlay

<img width="1312" alt="Screen Shot 2023-07-05 at 11 58 17 AM" src="https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/da3f5728-5463-4b7f-97ea-ce7eb7ac6d1f">

**Comment by kdegarmo** [comment]
Set cart panel to 75vh and overflow-y set to auto to scroll.
