### ISSUE TITLE
Course Builder: Add Module adding to wrong section

### ISSUE THREAD

**Issue by kdegarmo** [GlobalUniversity/ArkTrainingNetwork#193]
First section is open, 2nd section is closed. Attempted to add module to section 3, module draft is added to 1st section.

![image](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129225548/dbc93f0d-683a-4cd5-b80c-4463d64e4ef8)

**Comment by MrBonham** [comment]
I tried this on a draft course and it seemed to work. When I tried with a course that was already published it was adding to the first section as described above. I was also on Administrator instead of instructor.

**Comment by ChrisLamberth** [comment]
I believe this issue is caused by adding the model to the last section clicked. The model is being added to the "Selected_Section" variable. So if you open several sections, and then click Add Module on a section that isn't that Selected Section, then it'll add it to which is.
