### ISSUE TITLE
Form Builder > Form Information section > New Form > Default Form Title View

### ISSUE THREAD

**Issue by kdegarmo** [GlobalUniversity/ArkTrainingNetwork#198]
When creating a new form in form builder, to title the form, I think it would be easier to have the default view set as the input field with the apply button (see proposed screenshot).

NOW: ![image](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129225548/b649e956-1724-43a3-93d1-ec6e1f1672ed)

PROPOSED: 
![image](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129225548/1890a3f9-b0f4-47a6-b103-8caf16aa4a6b)

**Comment by MrBonham** [comment]
Input is the default now instead of the text field.
