### ISSUE TITLE
Getting system confirmation modal when navigating to the Marketplace as a student

### ISSUE THREAD

**Issue by kdegarmo** [GlobalUniversity/ArkTrainingNetwork#200]
This is happening across multiple student accounts (KristinStudent and krdinstructor as student role).

![image](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129225548/ecc9fd16-512c-416d-a323-4eecb9561ada)

**Comment by MrBonham** [comment]
This has something to do with the new permissions that Sean and I added. It should show up saying you dont have permissions. but instead if just pops up and you can close. It only seems to be happening to new students created so somewhere in that create they are not getting the full set of permissions. Message me and I can try to give more details.
