### ISSUE TITLE
Instructor > Courses > Filter dropdown shows "Active Courses" 2x

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#201]
Instructor > Courses > Filter dropdown shows "Active Courses" 2x
<img width="417" alt="Screen Shot 2023-07-06 at 9 49 18 AM" src="https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/a9e41787-b75a-4fd0-9b0d-0eb923d39e00">

**Comment by josh-havens** [comment]
Removed duplicate menu item
