### ISSUE TITLE
instructor > logo vanished

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#202]
instructor > logo vanished. I can't seem to repeat the issue. Did someone recently upload an image to it?

<img width="439" alt="Screen Shot 2023-07-06 at 9 49 49 AM" src="https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/8dcc6b7f-3015-433c-9f5f-331b1136e995">

**Comment by ChrisLamberth** [comment]
This is a time-out issue on the image asset that comes from our settings in AWS. It's not a bug but is a bit annoying. Upon refreshing, the image will reappear. This will happen to all images.
