### ISSUE TITLE
instructor > course builder > starts on "content" tab, not "Home"

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#203]
instructor > course builder > starts on "content" tab, not "Home" when i navigate into the builder

<img width="483" alt="Screen Shot 2023-07-06 at 9 54 21 AM" src="https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/2820db19-3a79-443c-b284-3cb7101cf107">

**Comment by SAStevens1** [comment]
It always has started on Content
