### ISSUE TITLE
instructor > course builder > activities, every time you click something, this dialog box shows up. it's super annoying

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#204]
instructor > course builder > activities, every time you click something, this dialog box shows up. it's super annoying.
<img width="899" alt="Screen Shot 2023-07-06 at 10 05 21 AM" src="https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/18f0cd30-06fb-466a-8ac3-f16f3afaf8f9">

**Comment by SAStevens1** [comment]
This is by design because its an ACTIVE course. When you make changes here you might be affecting someone's course progress. This is to make you aware to the severity of that
