### ISSUE TITLE
instructore > cousre builder > add questions, the first and second options are tangled

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#205]
in this image, i clicked the second box. however, it ticked the first one.
<img width="849" alt="Screen Shot 2023-07-06 at 10 17 16 AM" src="https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/e59f526f-3ebe-4e65-9155-6fda8faea7c9">

it continued to do so. the third one works fine.
<img width="888" alt="Screen Shot 2023-07-06 at 10 17 36 AM" src="https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/1246e4f5-e13c-4472-9a39-ef7f5b78a18f">

then in preview, when you select either the first or second, it always ticks both.
<img width="294" alt="Screen Shot 2023-07-06 at 10 22 40 AM" src="https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/8c78b0d3-79cb-40e1-a193-eb562b0bcb2c">

**Comment by SAStevens1** [comment]
Built by design when two options have the same data "asd" is the same
