### ISSUE TITLE
Logic Model Settings -> Template create -> Report Notifications

### ISSUE THREAD

**Issue by AyappaA** [GlobalUniversity/ArkTrainingNetwork#208]
Two things:
1. Cannot get the search bar to work, no users show up when I type in a name or hit the search button
2. Search bar looks "unfinished" on the right side 
Wasn't able to add any users to this

<img width="1270" alt="Screen Shot 2023-07-06 at 5 00 33 PM" src="https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129342490/4e56b58d-edc2-4f6f-88a5-2a502b086e39">

**Comment by kdegarmo** [comment]
Not totally sure about the search part of this but I think Josh tweaked something in the User search with this push that may have fixed this issue. Check again and re-open if this is still an issue but it's working for me in Dev and Test environments. 

Also, changed the input of the search bar from fixed width to 100% width and that fixes the second issue. log any input fields that you see that look like this with the search or input fields that seem too narrow as I think SBBD changed something & I've been fixing as I find them.
