### ISSUE TITLE
Required fields in Form Viewer squishes the required text when user's question text gets too long.

### ISSUE THREAD

**Issue by ChrisLamberth** [GlobalUniversity/ArkTrainingNetwork#214]
When text gets too long in the questionText field, the Form Viewer field pushes "squishes" the "required" text into a vertical column. 

![Image](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129114434/38b5566d-b59f-472a-974c-97b4db945802)

**Comment by kdegarmo** [comment]
Set parent panel of question text and required text to wrap so this will pop the required text field down below the question text.
