### ISSUE TITLE
Administrator > Forum > + doesn't add a forum

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#220]
Administrator > Forum > + doesn't work, despite permission settings
![Screen Shot 2023-07-07 at 11 26 30 AM](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/3b0e52a1-be48-4a47-8353-a881617ebdef)

**Comment by SAStevens1** [comment]
Made a new Administrator and was able to add new forums, and also used an old Administrator and had the same success

![image](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129208341/056d0cbd-4cea-4cad-8ca2-bf5da0930387)

Could not recreate. Maybe a permission thing to that specific user
