### ISSUE TITLE
Administration > Users > Profile > activity, the navigation disappears

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#222]
Administration > Users > Profile > activity, the navigation disappears

![Screen Shot 2023-07-07 at 11 31 05 AM](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/a4c62fe9-fc3c-4ce9-88fc-d3ba18db4343)

**Comment by SAStevens1** [comment]
permissions issue, logged out
