### ISSUE TITLE
Administrator > Clicking marketplace does nothing, and it eliminates my active tab indicator on the nav rail

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#225]
Administrator > Clicking marketplace does nothing, and it eliminates my active tab indicator on the nav rail
![Screen Shot 2023-07-07 at 11 38 17 AM](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/30d0a8c7-e0df-4969-96e5-fd3cb1f5decf)

**Comment by SAStevens1** [comment]
Logged out, server call is not being made
