### ISSUE TITLE
Administrator > Users > programs, this probably isnt a bug but i don't understand this page

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#227]
Administrator > Users > programs, this probably isnt a bug but i don't understand this page
![Screen Shot 2023-07-07 at 11 41 45 AM](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/a95e2120-337d-4ada-8b37-8cf465369f8d)

**Comment by SAStevens1** [comment]
Please use the question tag for questions. As you said, this probably isn't a bug
