### ISSUE TITLE
Users 

### ISSUE THREAD

**Issue by AyappaA** [GlobalUniversity/ArkTrainingNetwork#229]
Not sure if this is something new and supposed to be this way, but the when I click on Users it shows no one 

<img width="1437" alt="Screen Shot 2023-07-07 at 6 19 59 PM" src="https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129342490/d2cf33df-a1a5-44dc-adb0-6e1040705b03">

**Comment by SAStevens1** [comment]
This is new with permissions, you'll probably have to go enable permissions again. Honestly, the easiest way is to just disable then reenable all your permissions for administrator.
