### ISSUE TITLE
Administrator > Styles > saving doesnt save but navigates away incorrectly

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#234]
saving doesnt save but navigates away incorrectly

https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/0392b146-9d8c-4f62-9a05-f795ed799b08

**Comment by MrBonham** [comment]
There was some extra stuff in the Save VLC that did not make sense to have in Branch Styles. I got rid of it and published before I did if it needs to be reverted. It seems to be working as intended and saving properly.
