### ISSUE TITLE
Delete Button on Reports Page of Logic Model

### ISSUE THREAD

**Issue by rikkibarton** [GlobalUniversity/ArkTrainingNetwork#244]
Hi there! On the Reports tab of the logic model, the trash can delete icon is next to the edit button. In our bid/request, we wanted it to pop up with a box that asks to confirm that you want to delete before deleting. I tested it and if clicked, that month's report is deleted immediately, no questions asked. We really need that feature added ASAP so since many people will be inputting data into each month's report, we don't want someone accidentally hitting that and deleting all of the entries.

**Comment by josh-havens** [comment]
Hotfixed in production and changed in dev. Added confirmation click to Logic_Model_Reports_Monthly_Report_List_Item and Logic_Model_Reports_Annual_Report_List_Item. Also fixed an issue where deleting the report wouldn't refresh the list of reports.
