### ISSUE TITLE
Signing in to https:/staff.globaluniversity.edu./? 

### ISSUE THREAD

**Issue by NDubovsky** [GlobalUniversity/ArkTrainingNetwork#254]
It tells me I have forgotten my user name. I enter the email attached to that account, it sends me my user name (the same one I have been entering). Copy and paste the name sent to me, it tells me I have forgotten my user name. Sends it to me again, and it still doesn't accept the name I have been entering and has been sent to me several times.

**Comment by SAStevens1** [comment]
I copied the URL in the title of this issue. Is this what you see?
![image](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129208341/78268726-c1fc-457d-a81d-0ea0704174fd)

If so try using this URL below:

https://staff.globaluniversity.edu/?
