### ISSUE TITLE
Staff Ark deletes module content after saving

### ISSUE THREAD

**Issue by NDubovsky** [GlobalUniversity/ArkTrainingNetwork#256]
Heather Van Allen and I have both tried to load courses. We can set up the sections, add the module, fill and save the module, publish and save. When I set up the next module, it deletes the filled module and reverts it back to draft. We cannot load in that staff Ark.

**Comment by NDubovsky** [comment]
Hi,
I can only go into Course Builder from Administrator.

This is from the Foundations for Christian Leadership. I had all of the modules filled and clicked on the add Module button and they emptied the two sections of Introduction and reverted them to draft even though I had published them.

Heather had the same problem in RES5023 Graduate Research and Writing. I can’t look at your course since you put a password on it, but if you have 3filled modules I would love to know how you did it.

Nelda Dubovsky
Graduate Curriculum Coordinator
Global University
1211 S. Glenstone
Springfield, MO 65804
(417) 862-9533 x2152
***@***.***

**Comment by MrBonham** [comment]
Hello, 

![Screenshot 2023-09-12 at 9 16 06 AM](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/128522455/488b6900-a2bf-4af2-8c10-8c27c25925c1)

This is your course I added some modules and it was saving correctly. Are you hitting "Save" before you are adding a new module or how often are you hitting the save button?

**Comment by NDubovsky** [comment]
After adding or changing anything.

Nelda Dubovsky
Graduate Curriculum Coordinator
Global University
1211 S. Glenstone
Springfield, MO 65804
(417) 862-9533 x2152
***@***.***

**Comment by NDubovsky** [comment]
Good Morning,
I just went in and put my materials back. Saved it – several times. Then changed the modules you added. It kept the title I put in but reverted to your test line. I did it twice. I don’t know how you are entering this but would love to know. You have also added minutes to complete that I can’t get rid of.

Nelda Dubovsky
Graduate Curriculum Coordinator
Global University
1211 S. Glenstone
Springfield, MO 65804
(417) 862-9533 x2152
***@***.***

**Comment by SAStevens1** [comment]
Nelda, I checked your permissions and it looks like you don't have permissions to edit courses. I would recommend contacting whoever set your permissions and see if this resolves the issue.

![image](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129208341/60ca022f-762b-4898-b9e3-98d45154bcbc)

**Comment by NDubovsky** [comment]
Good Morning,
As of 6 AM I still can’t save in the Staff Ark. There is nothing else I can see in the Staff Ark. Perhaps  you should move some courses over from one of the other branches so we can start training our people?

Nelda Dubovsky
Graduate Curriculum Coordinator
Global University
1211 S. Glenstone
Springfield, MO 65804
(417) 862-9533 x2152
***@***.***

**Comment by ChrisLamberth** [comment]
@NDubovsky we talked about this yesterday and how I would have to come and look at what you are doing to get to the bottom of this. It looks as if you have been able to save sections and modules before, so I need to see what exactly is going on. If you are in the office today, let's set up a time to do that (over email, not here). This kind of comment doesn't help our developers sort through these issues. 

As for training, I mentioned several weeks ago that staff would have to be patient and wait until others made decisions about how things would work. I talked with Randy briefly about this yesterday and our plan/need to create new courses based on the data migration timeline. Please be patient. Let's set up a time so I can look at what's going on with the saving issues. To my knowledge, you and Heather are the only ones experiencing this issue. If you are working from home again today, perhaps a Zoom call would work.
