### ISSUE TITLE
Student Login: Cart Modal

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#26]
Shrunk: Cart spills out of window
Also, when you are looking at a product and click on “Go To Marketplace”, nothing happens.
![All about Kazakhstan](https://user-images.githubusercontent.com/129097082/228059536-53bcd28c-9e74-40f3-b957-d79d07356bad.png)

**Comment by MrBonham** [comment]
I added the VLC to Navigate to Marketplace. 

changed the size of cart panel to 250px seems to fit when shrunk.
