### ISSUE TITLE
Different user names for branches not recognized

### ISSUE THREAD

**Issue by marilynstefan** [GlobalUniversity/ArkTrainingNetwork#261]
When I enter into one of the branches (oticlassroom.com for example), and forget user name, the user name sent to me is only the one used for the GU branch.  

So my user name for the GU branch is mstefan1000 and for the other branches is mstefan with numbers ranging from 1-14.  The email sent to me when I forgot user name in oticlassroom.com was mstefan1000.  

Marilyn

**Comment by SAStevens1** [comment]
I believe this was an old data issue and has been taken care of. @josh-havens reopen this if this is not the case
