### ISSUE TITLE
Japan AG branch issues

### ISSUE THREAD

**Issue by marilynstefan** [GlobalUniversity/ArkTrainingNetwork#267]
I have set two different email accounts for verifications for this branch-the first is mstefan@globaluniversity.edu.  That email does not seem to be receiving the codes.  When I use my personal gmail account, I get this response.
![image](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129228337/57043e9e-903d-477c-a7d0-87328c9a1e2c)
This is the only branch that doesn't say the name of the branch in the email.

**Comment by SAStevens1** [comment]
This is not a Japan AG specific issue if its in relation to the title of the email. Its always been the same
