### ISSUE TITLE
Recovery Email form builder issues 

### ISSUE THREAD

**Issue by revwaggs** [GlobalUniversity/ArkTrainingNetwork#268]
Refer to previous bug report "Recovery Email #257"

I am in staff.globaluniversity.edu, version 1.0.10.

I have edited previously created draft forms. And I have created a new test form.

This issue is still occurring. When I set up an email question and enter "Recovery Email" in the field

![image](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/143851676/98969685-cade-4e85-9aba-fd16c5523bb3)

It does not show that way on the actual form.
![image](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/143851676/b75fe15f-5773-43c0-88b8-a0b0067e7038)

I am on my GU Windows laptop using the Chrome browser Version 118.0.5993.118 (Official Build) (64-bit)

**Comment by SAStevens1** [comment]
For whatever reason this fix didn't make it in the push between dev and test. I have implemented a hotfix in test that should resolve this issue. Thank you for bringing this to our attention!
