### ISSUE TITLE
Aiken Import - AACM and CATI

### ISSUE THREAD

**Issue by jimozias** [GlobalUniversity/ArkTrainingNetwork#269]
Importing questions via Aiken is no longer working. 

Copy and paste questions from Brackets. Click Preview. 

Result is usually a list of questions. Now, however, nothing is listed.

**Comment by SAStevens1** [comment]
Can you copy and paste a portion of the Brackets text you are using, please?

**Comment by jimozias** [comment]
It's working now. ;-)

**Comment by SAStevens1** [comment]
That's great to hear! I'll close this bug for now, but feel free to reference it again if the problem persists.
