### ISSUE TITLE
Student Login: Cart count persists

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#27]
After I checked out, the notification persisted even though the cart emptied.
![Checkout](https://user-images.githubusercontent.com/129097082/228059705-680c4b6c-15fc-43a7-89fe-e2c02177e496.png)

**Comment by MrBonham** [comment]
Added a Decision to look at the number of Items in the cart and if it was empty or 0 it updates to 0 now.
