### ISSUE TITLE
Student Login: Course Progress checkboxes

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#30]
What are these checkboxes? — I can’t interact with them
![Course Progress](https://user-images.githubusercontent.com/129097082/228062404-627a6daa-2ce4-4f1d-95f9-3218ad841e88.png)

**Comment by josh-havens** [comment]
Is this inside the Course Viewer?

**Comment by skruegergu** [comment]
this is inside course viewer.

**Comment by josh-havens** [comment]
These are progress boxes that fill in as you complete the modules.

**Comment by josh-havens** [comment]
I did see the column spacing issue on the list items here and fixed that.
