### ISSUE TITLE
Student Login:  Course Viewer Syllabus

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#32]
Do i have no grades, or do i and they failed to load?

![30450 Il about Kazakhstan](https://user-images.githubusercontent.com/129097082/228067715-e412acbc-538a-476d-ac2e-55507654e07f.png)

**Comment by ChrisLamberth** [comment]
- Modified API to return the Course Activity even if a module had not yet been assigned to it.
- Also added an empty list item cc to the Student's course activity list item view in the syllabus to give better feedback should a course activity not have a module assigned.
