### ISSUE TITLE
Pending Approval not working

### ISSUE THREAD

**Issue by MrBonham** [GlobalUniversity/ArkTrainingNetwork#33]
I created a new account. I have already logged in and bought a course on marketplace. But that user is still in the pending approval 

<img width="1079" alt="Screenshot 2023-03-28 at 9 03 45 AM" src="https://user-images.githubusercontent.com/128522455/228264396-7cba2cc5-f0d9-4c13-b41b-ffff552d7b10.png">

**Comment by josh-havens** [comment]
Need to rethink the UX of the URL settings authorization section. Toggle configurations allow this to happen.

**Comment by SAStevens1** [comment]
![image](https://user-images.githubusercontent.com/129208341/228899056-767af1ea-796f-44f7-9910-4f7739d170d7.png)

I was going to take this bug, but Pending Approval doesn't exist anymore. So for that reason............. I'm out

**Comment by josh-havens** [comment]
<img width="919" alt="Screen Shot 2023-03-30 at 12 12 56 PM" src="https://user-images.githubusercontent.com/128498837/228913499-bb158498-4e6f-4b34-9f13-d76592ec8295.png">
What u mean?

**Comment by josh-havens** [comment]
It's in dev. Could it be you found another bug?

**Comment by SAStevens1** [comment]
I hope not

**Comment by josh-havens** [comment]
Don't worry about this one though. It's not a bug here. It's actually a problem with the UX of the URL settings that allowed him to do this.

**Comment by SAStevens1** [comment]
Good

**Comment by josh-havens** [comment]
Setting this to backlog. It's functional at the moment and only requires a minute of training to avoid the issue. We will definitely change the UX on URL Settings in the future though.
