### ISSUE TITLE
Adding History as Student

### ISSUE THREAD

**Issue by MrBonham** [GlobalUniversity/ArkTrainingNetwork#37]
When adding history as a Student there is an ADD button and a Save button 

Add - Adds the course to the history
Save- closes the pop up and does not add

<img width="636" alt="Screenshot 2023-03-28 at 9 38 21 AM" src="https://user-images.githubusercontent.com/128522455/228274617-b80493cb-343e-4706-807e-80b979e2c16c.png">

**Comment by ChrisLamberth** [comment]
Added a hide UI task to hide buttons in the postload.
