### ISSUE TITLE
Student Login: Did the page not load or do I not have a history?

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#4]
Did the page not load or do I not have a history? If I don't have a history, we may need to align this with our current styling of "No [fill in the blank]" Either way as it stands, the signals are not clear.

![Stephen Krueger 9](https://user-images.githubusercontent.com/129097082/228030934-41777e66-f0f5-4116-82c2-399eb4754359.png)

**Comment by SAStevens1** [comment]
![image](https://user-images.githubusercontent.com/129208341/228861989-2540fae0-4f75-4866-9337-69e510ac5f34.png)
![image](https://user-images.githubusercontent.com/129208341/228862070-24cbe0af-6999-4896-911a-edb2ec7e1c48.png)
![image](https://user-images.githubusercontent.com/129208341/228862297-e8c825b8-f830-43b3-90e7-f0a044df243a.png)

Tested 3 different users. 2 in Dev and one in Test. I'm going to guess you were logged out or something? I can't see what you were logged in as to test fully, but I could not recreate this bug so.
