### ISSUE TITLE
Student Login: Course Viewer Messages

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#40]
If I search for someone I never sent a message to, they persist in the left column as if we have a thread. I Have never sent Mario Arango a message.
![Syllabus](https://user-images.githubusercontent.com/129097082/228293489-44de178d-343c-4b59-94e7-006c00b1a446.png)

Then when I search, and select someone I’ve Never messaged, my name gets entered into the list. This feels confusing. When I leave and return, my name is replaced by the person I searched for.
![Syllabus](https://user-images.githubusercontent.com/129097082/228293864-d14415a1-b0b1-4c39-adaa-a56873c9f838.png)

**Comment by josh-havens** [comment]
Changed API_Discussion_Add_DirectMessage to sort userIds and use that to create the messageID. Also added a tweak to ignore current user when adding a profile image and instead only use the targeted user's profile image. Need to possibly patch Discussion_Channels records to avoid duplicate message threads between the same people.
