### ISSUE TITLE
Course Modules can be rearranged in the Section, but even after saving it does not update the list on the left side and when you click the Section it reverts to the left sides order rather than what was saved on the main panel.

### ISSUE THREAD

**Issue by SAStevens1** [GlobalUniversity/ArkTrainingNetwork#44]
![image](https://user-images.githubusercontent.com/129208341/228342430-8b29d029-05ff-4dae-8302-70dfabbc9046.png)
![image](https://user-images.githubusercontent.com/129208341/228357907-136e4d24-1504-4923-b09c-b1c8c1d97437.png)

**Comment by josh-havens** [comment]
Fixed API_CourseContent_Edit_Section to save the modules sequence numbers.
