### ISSUE TITLE
Instructor Login: Active Courses Tab x2

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#45]
![Courses](https://user-images.githubusercontent.com/129097082/228360048-4df1f38d-85f3-4106-8bf4-d7aed0914ca4.png)

**Comment by josh-havens** [comment]
We've rearranged the Course Manager menu. Everything now appears under the filter menu. This also fixed the issue with two "Active Courses" items showing up.
