### ISSUE TITLE
Administrator Login: Course Assingment User Search

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#46]
This is difficult to identify users because User Names are absent.

![Search By](https://user-images.githubusercontent.com/129097082/228360176-cec99e81-25f0-4f34-ae66-308bf6f3d7ef.png)

**Comment by josh-havens** [comment]
Need to change the email to the username to bring it into alignment with the rest of the places we show a user list item like this.

**Comment by josh-havens** [comment]
Added username and made the username/email font smaller.
