### ISSUE TITLE
Instructor Login: Course Scheduler Delete

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#47]
Deleting doesn’t delete
![Draft Cours](https://user-images.githubusercontent.com/129097082/228360510-cf732109-32fb-42b0-98bb-7d7ccf1aa138.png)

**Comment by josh-havens** [comment]
Instructors shouldn't see the course scheduler. Can you try deleting from the Administrator role and see if that works?
