### ISSUE TITLE
Instructor Login: Course Scheduler Past Schedules

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#48]
Why do I have all of these past schedules? I did not make them, nor was I assigned them
![Screen Shot 2023-03-28 at 2 22 53 PM](https://user-images.githubusercontent.com/129097082/228360654-e6c60dc0-7f04-4fa5-bca9-7f40ffc10230.png)

**Comment by ChrisLamberth** [comment]
This issue was fixed when the Course Schedule menu item was moved from the Course Manager into the Academic Settings area of the Branch.
