### ISSUE TITLE
Forms: New Form Button

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#50]
Why is this + button different from every other + button?
![Active Forms](https://user-images.githubusercontent.com/129097082/228367111-b4f1c182-980c-40c8-9e2d-821d31b6720b.png)

**Comment by kdegarmo** [comment]
There are actually two add icons here, one is hidden. There will be two options of form creation: new account creation form and new survey form. Right now, we're only using the account creation form but eventually we'll use survey so there are two icons to differentiate between which new form you're creating.
