### ISSUE TITLE
Two accounts same email works

### ISSUE THREAD

**Issue by marilynstefan** [GlobalUniversity/ArkTrainingNetwork#57]
I created a new student acct fredacct4 in the admin with a unique email address.  When logging in, I clicked “Forgot pw” and it sent an email to that email address.  

However the URL is only printed in the email and is not set as a link.  See this screenshot of the email:
https://capture.dropbox.com/h6fGUvPY7VgWoHGE

**Comment by josh-havens** [comment]
This is an issue related to the mail client. Different mail clients interpret the URL value differently. We have no way to guarantee an email client will behave in a certain way.
