### ISSUE TITLE
Full welcome screen not showing

### ISSUE THREAD

**Issue by marilynstefan** [GlobalUniversity/ArkTrainingNetwork#58]
I created a new student acct fredacct4 in the admin with a unique email address.  When logging in, I clicked “Forgot pw” and it sent an email to that email address.  

However the URL is only printed in the email and is not set as a link.  See this screenshot of the email:
https://capture.dropbox.com/h6fGUvPY7VgWoHGE (Prior bug sent in)

Once I copied the link into the browser, I was able to set it, but did not get a full welcome screen.
https://capture.dropbox.com/liBPRRrAlVg17yUi

**Comment by josh-havens** [comment]
Changed the reset password link generation to pull from the baseURL of API_AuthenticationRequest. Also tweaked manipulate UI tasks in Login_Main_Click and Login_Password_Reset_Check.
