### ISSUE TITLE
As a Student in a course when you are in Forum, you can hit the Hamburger button circled below and this is the result. Note: The Main Panel will not change when you click the Menu buttons

### ISSUE THREAD

**Issue by SAStevens1** [GlobalUniversity/ArkTrainingNetwork#59]
![image](https://user-images.githubusercontent.com/129208341/228374076-cf64fb92-5cce-4f8f-ad7d-aea198d498db.png)

**Comment by SAStevens1** [comment]
![image](https://user-images.githubusercontent.com/129208341/228374952-73b8fe94-19f3-448b-8897-b8f2ec7c0b2d.png)
 
 Same with Messages

**Comment by ChrisLamberth** [comment]
- Added a Disable UI task to disable the hamburger menu when selecting Forums as well as Messaging from inside the course viewer. Added an Enable UI task to enable the hamburger menu in Course_Viewer_Menu_Item_Click so clicking one of the other menu items enables it. 
- Also fixed an issue where the menu toggle value wasn't being set correctly when entering the Course Viewer.
