### ISSUE TITLE
Student Login: Text stays a little crunched up when screen is expanded

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#6]
Text stays a little crunched up when screen is expanded
![Screen Shot 2023-03-27 at 10 33 00 AM](https://user-images.githubusercontent.com/129097082/228032246-70210dd4-b501-467e-9c74-1572d143036d.png)

**Comment by kdegarmo** [comment]
Changed max width of user program and history to 1200px instead of 1000px.
