### ISSUE TITLE
Education History Modal UI

### ISSUE THREAD

**Issue by SAStevens1** [GlobalUniversity/ArkTrainingNetwork#61]
![image](https://user-images.githubusercontent.com/129208341/228562011-b2cf3e2d-d28b-4f04-b5b1-3a1c9a3b6290.png)

**Comment by kdegarmo** [comment]
min-height of this modal is set to 400px. If we can't/don't want to change that, do you want me to just make the content fit inside 400px?

**Comment by kdegarmo** [comment]
Adjusted content to fit inside 400px modal on most screen sizes. If a user is forcing a smaller window, they might run into the issue but likely won't be a concern moving forward.
