### ISSUE TITLE
Student Login: Did the page not load or do I not have courses?

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#7]
Did the page not load or do I not have courses? Again, if I have no courses, this UI is incongruent with other sections of the website -- which do provide good feedback.
![en Krueger](https://user-images.githubusercontent.com/129097082/228035095-4ee3ca43-720c-4758-89a0-08948f1e7de4.png)

**Comment by ChrisLamberth** [comment]
The global Variable data model wasn't updated to SysQueryResults.
