### ISSUE TITLE
Administrator>Branch>User Settings>Add Label // the 5 label type buttons do nothing

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#71]
Clicking any of the five buttons does nothing. During debugging, the status of the Main_Web_Service_Caller is FAILED.

<img width="660" alt="Screen Shot 2023-03-29 at 11 17 18 AM" src="https://user-images.githubusercontent.com/129097082/228602602-a6502f3d-2522-4068-b4ab-9df0647e7480.png">

**Comment by josh-havens** [comment]
20:37:25.655 [http-nio-80-exec-454] ERROR c.d.r.dao.redis.RedisCacheService - REDIS : Null value from redis for key STEPHENADMITEST and cache name RR__user_5f47ce0c8f0815394ff3bd8a
code:MISSING_DATA customErrorAttributes:null Missing required field branchId

**Comment by ChrisLamberth** [comment]
Was not adding the field to Branch_CustomFields because a Branch_CustomFields record had not yet been created. 

- I added a create Branch_CustomFields record process in API_Branch_Get_CustomFields if one was not found.
