### ISSUE TITLE
GPA Calculations

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#72]
Clicking "+Add" does not add

<img width="1026" alt="Screen Shot 2023-03-29 at 11 54 41 AM" src="https://user-images.githubusercontent.com/129097082/228612124-1df99566-32d9-4cf8-ab8b-110c2f2c3ffc.png">

**Comment by josh-havens** [comment]
Have you debugged to see what might be happening?

**Comment by ChrisLamberth** [comment]
Added Permission. Also added a UI task that hides the input field after the GPA Calc has been created.
