### ISSUE TITLE
Educational history needs edit or delete button

### ISSUE THREAD

**Issue by marilynstefan** [GlobalUniversity/ArkTrainingNetwork#78]
No way to correct or eliminate once created. 
![image](https://user-images.githubusercontent.com/129228337/228637478-43c01ebb-a151-4d36-ae82-52da72ca1797.png)

**Comment by josh-havens** [comment]
Edit is there and functional. There is no delete button inside the overlay modal.

**Comment by josh-havens** [comment]
Added a delete button inside the edit popup.
