### ISSUE TITLE
Can't seem to show courses on the instructor mode

### ISSUE THREAD

**Issue by marilynstefan** [GlobalUniversity/ArkTrainingNetwork#79]
1.  I've double checked permissions and turned them off and on
2. I've this course-Budgeting with me as the instructor
3.
![image](https://user-images.githubusercontent.com/129228337/228639524-83ca2cd7-d3e6-4a13-a750-632a7f1feba1.png)
4.  refreshed and then entered as instructor
5. 
![image](https://user-images.githubusercontent.com/129228337/228639873-a81d7581-031f-457c-9d63-b6b5201dac9d.png)
6. This shows
7. 
![image](https://user-images.githubusercontent.com/129228337/228640109-a955babe-e53b-418a-861d-2eb2151e19b6.png)

**Comment by josh-havens** [comment]
Instructor query wasn't set up for pagination in the API
