### ISSUE TITLE
Site Builder > Marketplaces > +

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#81]
Clicking save resulted in an error modal.
<img width="1391" alt="Screen Shot 2023-03-29 at 3 34 02 PM" src="https://user-images.githubusercontent.com/129097082/228660803-0e7486ae-7650-42e8-9efb-0e0649b19713.png">

**Comment by MrBonham** [comment]
I did not get an Error message when I tried clicking the same on a Administrator only account. I might need more info to help figure out what might have caused the error. screen shot of the reasons from the debug tool perhaps.
