### ISSUE TITLE
Account Creation with the isrequired field

### ISSUE THREAD

**Issue by MrBonham** [GlobalUniversity/ArkTrainingNetwork#82]
When Creating a new account the isrequired* field I think it looks at the whole address even if you do not have the field selected. 

![Screenshot 2023-03-29 at 3 48 44 PM](https://user-images.githubusercontent.com/128522455/228664041-2b1c3e5c-db18-47a7-a3cd-96b53f6506b6.png)

Example. address2 was not added to the list of required but I think it still does a check on if it is answered. 

![Screenshot 2023-03-29 at 3 49 51 PM](https://user-images.githubusercontent.com/128522455/228664076-89271e98-9f32-4c28-acd9-c9ddf8d9c339.png)

Dont mind the first name last name I did not fill those in they were working as intended.

**Comment by SAStevens1** [comment]
Fixed this when we reworked address
