### ISSUE TITLE
Instructor Settings Ranks and Types

### ISSUE THREAD

**Issue by josh-havens** [GlobalUniversity/ArkTrainingNetwork#83]
Branch_Instructor_Settings_Add_Rank needs a little TLC in the UX/UI department. At the very least it needs a label on the input field.

**Comment by kdegarmo** [comment]
Tidy up Branch Instructor Settings Main UI (mainly widths, spacing, etc.) and add input CCs.

![image](https://user-images.githubusercontent.com/129225548/229008588-13d159d1-cc43-42f2-92cd-e1036c569ff2.png)
