### ISSUE TITLE
Dropdown menu arrow

### ISSUE THREAD

**Issue by AyappaA** [GlobalUniversity/ArkTrainingNetwork#86]
Dropdown for profile, arrow does not switch directions when opened/closed

<img width="418" alt="Screen Shot 2023-03-27 at 8 00 41 PM" src="https://user-images.githubusercontent.com/129342490/228696790-1e4edde9-9311-41aa-8ac6-ab69c9bc6d19.png">

<img width="418" alt="Screen Shot 2023-03-27 at 7 59 59 PM" src="https://user-images.githubusercontent.com/129342490/228696802-e0652c3d-f5c4-4496-99ba-493d10ece8ef.png">

**Comment by skruegergu** [comment]
I duplicated the chevron button in the CC User_Info_Teaser and hid it. In the VLC User_Info_Show_Role_SubMenu, I add two UI tasks (one hide, one show) to each fork of the decision. Now the chevron switches between up and down when clicked on the dev site.
