### ISSUE TITLE
Adding tag to User

### ISSUE THREAD

**Issue by AyappaA** [GlobalUniversity/ArkTrainingNetwork#87]
Can the popup verification box be big enough to not have a scroll bar so it all can be seen

<img width="1170" alt="Screen Shot 2023-03-28 at 6 51 59 PM" src="https://user-images.githubusercontent.com/129342490/228697067-7f393076-55c8-4e77-bdb5-03c44e32d0d4.png">

<img width="1170" alt="Screen Shot 2023-03-28 at 6 52 03 PM" src="https://user-images.githubusercontent.com/129342490/228697076-28b02f4b-bd90-42ad-9352-a15d159cd220.png">

**Comment by skruegergu** [comment]
Team,

I tracked this issue to the VLC Exit task on User_Account_Administrator_Settings_Add_Admin_Tag_Search_List_Item_Click. On the exit task, i removed the Modal height.
