### ISSUE TITLE
"My Account" vs "Users" account options

### ISSUE THREAD

**Issue by AyappaA** [GlobalUniversity/ArkTrainingNetwork#89]
Order of account options are not consistent; Profile Information and Online Activity in different orders

<img width="1437" alt="Screen Shot 2023-03-28 at 6 53 00 PM" src="https://user-images.githubusercontent.com/129342490/228699169-2315385f-0573-4416-a378-e9336301efab.png">

<img width="1437" alt="Screen Shot 2023-03-28 at 6 53 08 PM" src="https://user-images.githubusercontent.com/129342490/228699180-d958718d-cb32-4090-84a2-a47b07412adb.png">

**Comment by skruegergu** [comment]
I used the Data manager to add seq numbers to the cards so they show in the same order in both place
